### ISSUE TITLE
Request for new subdomain

### ISSUE THREAD

**Issue by JobNmadu** [rbind/support#734] opened 2021-01-05 20:32 UTC
## Netlify website address

https://dreamy-rosalind-7536f8.netlify.app/

## Preferred rbind.io subdomain

jobnmadu.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment] 2021-01-06 16:39
Closing as superseded by https://github.com/rbind/support/issues/736

**Comment by JobNmadu** [comment] 2021-02-20 21:15
my subdomain jobnmadu.rbind.io is not propagating well and it seems there
are issues with the approval. Is there anything to be done to ensure that
everything works fine?

Job N Nmadu. *experience*, *expertise*, efficiency:* eternity in view!*
Professor, Department of Agricultural Economics and Farm Management

Industrial Liaison Officer, Federal University of Technology, Minna,
Nigeria *(**www.futminna.edu.ng <http://www.futminna.edu.ng/>**)*

&

President and Fellow, Nigerian Association of Agricultural Economists
(*www.naae.org.ng
<http://www.naae.org.ng/>*)

*www.jobnmadu.blogspot.com <http://www.jobnmadu.blogspot.com/>*
job_nmadu@futminna.edu.ng

job_nmadu@yahoo.co.uk
<job.nmadu@gmail.com>

**Comment by nanxstats** [comment] 2021-02-23 23:44
@JobNmadu -there are no issues in approval, the propagation looks ok too. The 404 is from the source site `cranky-lewin-527ae0.netlify.app` - make sure this site is available on Netlify.

**Comment by JobNmadu** [comment] 2021-02-24 01:25
Okay, thanks. I have restored the file to the site and nothing happened
yet. Is there anything further I need to do?

Job N Nmadu. *experience*, *expertise*, efficiency:* eternity in view!*
Professor, Department of Agricultural Economics and Farm Management

Industrial Liaison Officer, Federal University of Technology, Minna,
Nigeria *(**www.futminna.edu.ng <http://www.futminna.edu.ng/>**)*

&

President and Fellow, Nigerian Association of Agricultural Economists
(*www.naae.org.ng
<http://www.naae.org.ng/>*)

*www.jobnmadu.blogspot.com <http://www.jobnmadu.blogspot.com/>*
job_nmadu@futminna.edu.ng

job_nmadu@yahoo.co.uk
<job.nmadu@gmail.com>

**Comment by nanxstats** [comment] 2021-02-25 02:17
I'm sorry but I have no idea here. I'm looping in @yihui for help.

The issue is that the subdomain `jobnmadu.rbind.io` shows a 404 for upstream `cranky-lewin-527ae0.netlify.com` (which might be removed then re-added). It used to work though. Maybe remove and re-add the cname record would help?

**Comment by JobNmadu** [comment] 2021-02-26 04:23
Thanks for the feedback. I tried all your suggestions but nothing
has changed yet. Could it be an error from the hugo heme I used? The theme
is "stip-hugo". I have produced here the nature of error from the
subdomains attached to my account, maybe it helps.

[image: image.png]


Job N Nmadu. *experience*, *expertise*, efficiency:* eternity in view!*
Professor, Department of Agricultural Economics and Farm Management

Industrial Liaison Officer, Federal University of Technology, Minna,
Nigeria *(**www.futminna.edu.ng <http://www.futminna.edu.ng/>**)*

&

President and Fellow, Nigerian Association of Agricultural Economists
(*www.naae.org.ng
<http://www.naae.org.ng/>*)

*www.jobnmadu.blogspot.com <http://www.jobnmadu.blogspot.com/>*
job_nmadu@futminna.edu.ng

job_nmadu@yahoo.co.uk
<job.nmadu@gmail.com>

**Comment by yihui** [comment] 2021-02-26 04:29
@nanxstats I didn't do anything, and the domain jobnmadu.rbind.io works fine for me at the moment:

![image](https://user-images.githubusercontent.com/163582/109255007-c9e75180-77b8-11eb-83b1-5394d5b73ba7.png)

**Comment by JobNmadu** [comment] 2021-02-26 05:12
Yes, you are right, but only this page propagates, the public folder is not
propagated. Thanks.

Job N Nmadu. *experience*, *expertise*, efficiency:* eternity in view!*
Professor, Department of Agricultural Economics and Farm Management

Industrial Liaison Officer, Federal University of Technology, Minna,
Nigeria *(**www.futminna.edu.ng <http://www.futminna.edu.ng/>**)*

&

President and Fellow, Nigerian Association of Agricultural Economists
(*www.naae.org.ng
<http://www.naae.org.ng/>*)

*www.jobnmadu.blogspot.com <http://www.jobnmadu.blogspot.com/>*
job_nmadu@futminna.edu.ng

job_nmadu@yahoo.co.uk
<job.nmadu@gmail.com>

**Comment by nanxstats** [comment] 2021-02-26 07:02
Great, thanks @yihui. It also works on my side now. Testing from the 6 locations on https://geopeeker.com also confirms it's working. Maybe it was some transient network issue.

**Closed by nanxstats** 2021-02-26 07:02 UTC

**Comment by JobNmadu** [comment] 2021-03-06 15:26
Can you please re-initialise jobnmadu.rbind.io. There is still an
unresolved issue with the subdomain. Thanks.

Job N Nmadu. *experience*, *expertise*, efficiency:* eternity in view!*
Professor, Department of Agricultural Economics and Farm Management

Industrial Liaison Officer, Federal University of Technology, Minna,
Nigeria *(**www.futminna.edu.ng <http://www.futminna.edu.ng/>**)*

&

President and Fellow, Nigerian Association of Agricultural Economists
(*www.naae.org.ng
<http://www.naae.org.ng/>*)

*www.jobnmadu.blogspot.com <http://www.jobnmadu.blogspot.com/>*
job_nmadu@futminna.edu.ng

job_nmadu@yahoo.co.uk
<job.nmadu@gmail.com>

**Comment by nanxstats** [comment] 2021-03-07 22:05
Hey @JobNmadu this is what I see:

![Screen Shot 2021-03-07 at 4 59 34 PM](https://user-images.githubusercontent.com/199363/110256371-96e65000-7f66-11eb-913d-fe0527740987.png)

It looks like the subdomain is globally accessible, and still points to `cranky-lewin-527ae0.netlify.com`. So I'm not sure what can be done here... Do you want us to point it to another site?
