### ISSUE TITLE
New rbind.io subdomain request

### ISSUE THREAD

**Issue by byngdeuk** [rbind/support#361] opened 2019-02-11 03:17 UTC
## Netlify website address

determined-albattani-bb5595.netlify.com

## Preferred rbind.io subdomain

byngdeuk.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment] 2019-02-11 07:07
Hi @byngdeuk -we're happy to offer the subdomain, while it looks like there is not any content at the Netlify website yet (a soft 404). Would you mind adding something there first, please? Thank you!

**Comment by road2stat** [comment] 2019-02-11 17:37
Duplicate of https://github.com/rbind/support/issues/363 so closing for now.

**Closed by road2stat** 2019-02-11 17:37 UTC
