### ISSUE TITLE
Request for rbind.io subdomain

### ISSUE THREAD

**Issue by brendonkoh** [rbind/support#926] opened 2022-12-24 23:17 UTC
## Netlify website address

brendonkoh-portfolio.netlify.app

## Preferred rbind.io subdomain

brendon.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment] 2023-01-04 17:27
@brendonkoh We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by brendonkoh** [comment] 2023-01-06 20:27
Hello @nanxstats thanks so much for your help with this!

I have some issues adding the subdomain as a custom domain - it states that the subdomain is already being managed by another team. Would you have any suggestions on how I could work around this?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/120264123/211093771-3c5e7dad-aa61-477a-8881-b457eafe553a.png">

Best,
Brendon

**Comment by nanxstats** [comment] 2023-01-06 23:23
@yihui Now I also see the same message above when adding a rbind.io subdomain on Netlify. Do you see the same issue?

**Comment by yihui** [comment] 2023-01-07 02:15
Sorry I have no idea what that means. At least rbind.io is not managed by Netlify DNS. I'm not sure if anyone else set up their subdomain with Netlify DNS, and don't know how to find it out...

**Comment by nanxstats** [comment] 2023-01-07 09:36
ChatGPT tells me to use `dig`, which is technically correct and impresive.

```bash
#!/bin/bash

while read subdomain; do
  ns=$(dig +short NS "$subdomain")
  if [[ "$ns" =~ "netlifydns.com" ]]; then
    echo "$subdomain is managed by Netlify DNS"
  else
    echo "$subdomain is not managed by Netlify DNS"
  fi
done < subdomains.txt
```

However, the result is not useful because that's unlikely the root cause here.

Maybe folks from Netlify updated some of their backend logic? I see this exact question is poping up on their support site since last week. For example: [2022-12-26](https://answers.netlify.com/t/82021), [2022-12-28](https://answers.netlify.com/t/82145), [2022-12-30](https://answers.netlify.com/t/82247), [2023-01-05](https://answers.netlify.com/t/82540).

**Comment by nanxstats** [comment] 2023-01-20 15:30
Looks like it's working now - so I'm closing this.

**Closed as completed by nanxstats** 2023-01-20 15:30 UTC
